apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: mycustomdatabases.wim-vdw.io
spec:
  group: wim-vdw.io
  scope: Namespaced
  names:
    plural: mycustomdatabases
    singular: mycustomdatabase
    kind: MyCustomDatabase
    shortNames:
    - mcd
    - mcds
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              databaseSizeGb:
                type: integer
              region:
                type: string
              highAvailability:
                type: boolean
          status:
            type: object
            properties:
              phase:
                type: string
    additionalPrinterColumns:
    - name: Size
      type: integer
      jsonPath: .spec.databaseSizeGb
      description: Size of the database in GB
      priority: 0
    - name: Region
      type: string
      jsonPath: .spec.region
      description: Region where the database is hosted
      priority: 1
    - name: HA
      type: boolean
      jsonPath: .spec.highAvailability
      description: High Availability enabled
      priority: 1
    - name: Phase
      type: string
      jsonPath: .status.phase
      description: Current phase of the database
      priority: 0
