apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: mycustomdatabases.wim-vdw.io
spec:
  group: wim-vdw.io
  scope: Namespaced
  names:
    plural: mycustomdatabases
    singular: mycustomdatabase
    kind: MyCustomDatabase
    shortNames:
    - mcd
    - mcds
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              highAvailability:
                type: boolean
              region:
                type: string
              databaseSizeGb:
                type: integer
